#!/bin/bash

FILES=$@

if [[ $# -eq 0 ]]; then
    FILES="**/*"
fi

echo "Watching $FILES"

while WATCH=$(inotifywait --event close_write $FILES);
do
    FILE=$(echo $WATCH | cut --delimiter=' ' --fields=1);
    if [[ $FILE == "lwc/"* ]]; then
        sfdx force:source:deploy --sourcepath=$(echo $FILE | cut --delimiter=. --fields=1 | cut --delimiter=/ --fields=1-2)
    else 
        sfdx force:source:deploy --sourcepath=$FILE
    fi
done
