#!/bin/bash

FILES=$@

if [[ $# -eq 0 ]]; then
    FILES="**/*"
fi

echo "Watching $FILES"

while WATCH=$(inotifywait -e close_write $FILES);
do
    FILE=$(echo $WATCH | cut -d' ' -f1);
    if [[ $FILE == "lwc/"* ]]; then
        sfdx force:source:deploy -p $(echo $FILE | cut -d. -f1 | cut -d/ -f1-2)
    else 
        sfdx force:source:deploy -p $FILE
    fi
done
